@startuml
scale max 4096 width
skinparam nodesep 100
hide circle

class merknad {
  <b>merkandstekst</b>
  merknadstype
  <b>merknadsdato</b>
  <b>merknadRegistrertAv</b>
}

class skjerming {
  <b>tilgangsrestriksjon</b>
  <b>skjermingshjemmel</b>
  <b>skjermingMetadata</b>
  skjermingDokument
  skjermingsvarighet
  skjermingOpphoererDato
}

class utfoertKassasjon {
  <b>kassertDato</b>
  <b>kassertAv</b>
}

class kassasjon {
  <b>kassasjonsvedtak</b>
  kassasjonshjemmel
  <b>bevaringstid</b>
  <b>kassasjonsdato</b>
}

class gradering {
  <b>gradering</b>
  <b>graderingsdato</b>
  <b>gradertAv</b>
  nedgraderingsdato
  nedgradertAv
}

class elektroniskSignatur {
  <b>elektroniskSignaturSikkerhetsnivaa</b>
  <b>elektroniskSignaturVerifisert</b>
  <b>verifisertDato</b>
  <b>verifisertAv</b>
}

class part {
  partID
  <b>partNavn</b>
  <b>partRolle</b>
  postadresse
  postnummer
  poststed
  land
  epostadresse
  telefonnummer
  kontaktperson
  virksomhetsspesifikkeMetadata
}

class dokumentbeskrivelse {
  <b>systemID</b>
  <b>dokumenttype</b>
  <b>dokumentstatus</b>
  <b>tittel</b>
  beskrivelse
  forfatter
  <b>opprettetDato</b>
  <b>opprettetAv</b>
  dokumentmedium
  oppbevaringssted
  referanseArkivdel
  <b>tilknyttetRegistreringSom</b>
  <b>dokumentnummer</b>
  <b>tilknyttetDato</b>
  <b>tilknyttetAv</b>
}

class dokumentobjekt {
  <b>systemID</b>
  <b>versjonsnummer</b>
  <b>variantformat</b>
  <b>format</b>
  formatDetaljer
  <b>opprettetDato</b>
  <b>opprettetAv</b>
  <b>referanseDokumentfil</b>
  <b>sjekksum</b>
  <b>sjekksumAlgoritme</b>
  <b>filstoerrelse</b>
}

class sletting {
  <b>slettingstype</b>
  <b>slettetDato</b>
  <b>slettetAv</b>
}

class konvertering {
  <b>konvertertDato</b>
  <b>konvertertAv</b>
  <b>konvertertFraFormat</b>
  <b>konvertertTilFormat</b>
  konverteringsverktoey
  konverteringskommentar
}

class registrering

registrering "1..*" o--> "0..*" dokumentbeskrivelse
dokumentbeskrivelse "1" o-> "0..*" dokumentobjekt
dokumentobjekt "1" o-> "0..*" konvertering

part "0..*" <--o "0..*" dokumentbeskrivelse
sletting "0..1" <-o "0..*" dokumentbeskrivelse

merknad "0..*" <--o "0..*" dokumentbeskrivelse
skjerming "0..1" <--o "0..*" dokumentbeskrivelse
utfoertKassasjon "0..1" <--o "0..*" dokumentbeskrivelse
dokumentbeskrivelse "0..*" o--> "0..1" kassasjon
dokumentbeskrivelse "0..*" o--> "0..1" gradering
dokumentbeskrivelse "0..*" o--> "0..1" elektroniskSignatur
dokumentobjekt "0..*" o--> "0..1" elektroniskSignatur

@enduml
