' FIXME missing constraints 'enten/eller'
@startuml
scale max 4096 width
skinparam nodesep 100
allowmixing
hide circle

class arkiv
class arkivdel
class klassifikasjonssystem
class klasse
class mappe
class registrering
class dokumentbeskrivelse
class dokumentobjekt
rectangle "Elektronisk dokument"

arkivdel "0..*" <.. mappe

arkiv "1" o--> "1..*" arkivdel
arkiv "0..*" o-> "1.*" arkiv : underarkiv
constraint on links: enten/eller

arkivdel "1..*" o--> "0..*" klassifikasjonssystem
arkivdel "1" o--> "0..*" mappe
constraint on links: enten/eller

klassifikasjonssystem "1" o--> "1..*" klasse
klasse "0..1" o--> "0..*" mappe

klasse "0..1" o-> "0..*" klasse : underklasse
klasse "1" o-> "0..*" registrering
constraint on links: enten/eller

mappe "1" o--> "0..*" registrering
mappe "0..1" o-> "0..*" mappe : undermappe

arkivdel "1" o--> "0..*" registrering
registrering "1..*" o--> "0..*" dokumentbeskrivelse
registrering .> "0..*" arkivdel
dokumentbeskrivelse "1" o--> "0..*" dokumentobjekt
dokumentbeskrivelse .> "0..*" arkivdel
dokumentobjekt . "1" "Elektronisk dokument"
@enduml
